package spanish.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 30 DE MARZO DE 2022 06:44:05 PM COT
 */
public class grmConfirmacion extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for grmConfirmacion.
    */
    public grmConfirmacion() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("es-la");
        setMode("dtmf");
        setBuiltin(true);
        setBuiltinMode("dtmf");
        setType("boolean");
        setOptions("y=1;n=2");
		//}}END:CLASS:CONSTRUCTOR
    }

}

