package spanish.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 30 DE MARZO DE 2022 04:40:08 PM COT
 */
public class grmDigitaNIT extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for grmDigitaNIT.
    */
    public grmDigitaNIT() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("es-la");
        setMode("dtmf");
        setBuiltin(true);
        setBuiltinMode("dtmf");
        setType("digits");
        setOptions("minlength=3;maxlength=11");
		//}}END:CLASS:CONSTRUCTOR
    }

}

