package connectivity.db.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the database operation is regenerated.
 * Last generated by Orchestration Designer at: 1 DE ABRIL DE 2022 09:17:50 AM COT
 */
public class ConsultaPrestador extends com.avaya.sce.runtime.connectivity.db.DbQuery {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for ConsultaPrestador.
	 * Last generated by Orchestration Designer at: 1 DE ABRIL DE 2022 09:17:50 AM COT
	 */
	public ConsultaPrestador( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
		super(mySession);

		setDataSourceName("jdbc/UATColmena");
		setDbObjectName("dbo.Arp_Prestadores_Ivr");
		setOperation(0);
		setReturnType(-1);
		setSQLQuery("SELECT Arp_Prestadores_Ivr.IdPrestador, Arp_Prestadores_Ivr.CodGrabacion FROM dbo.Arp_Prestadores_Ivr WHERE  ( Arp_Prestadores_Ivr.ID = ? )");

		// List variable that may be used
		java.util.List list;

		// Parameters
		com.avaya.sce.runtime.connectivity.db.DbQueryParam parameter;
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("IdPrestador",0,12, "UUIData"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("CodGrabacion",0,12, "UUIData"));

		// Where parameters
		addWhereParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("ID",0,4,"ConsultaPrestador:id"));

		//}}END:CLASS:CONSTRUCTOR
	}

}

