package connectivity.db.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the database operation is regenerated.
 * Last generated by Orchestration Designer at: 1 DE ABRIL DE 2022 09:05:15 AM COT
 */
public class InsertarDatos extends com.avaya.sce.runtime.connectivity.db.DbQuery {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for InsertarDatos.
	 * Last generated by Orchestration Designer at: 1 DE ABRIL DE 2022 09:05:15 AM COT
	 */
	public InsertarDatos( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
		super(mySession);

		setDataSourceName("jdbc/Produccion");
		setDbObjectName("dbo.ARP_Datos_Ivr_SP;1");
		setOperation(4);
		setReturnType(2);
		setSQLQuery("{ ? = call dbo.ARP_Datos_Ivr_SP;1 (  ?, ?) }");

		// List variable that may be used
		java.util.List list;

		// Parameters
		com.avaya.sce.runtime.connectivity.db.DbQueryParam parameter;
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("@RETURN_VALUE",5,4, "insertaDatosBD:resultado"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("@datos",1,12, "insertaDatosBD:datos"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("@llave",2,4, "insertaDatosBD:llave"));

		//}}END:CLASS:CONSTRUCTOR
	}

}

